name: Build & Release SusOps

on:
  push:
    tags:
      - 'v*'

# Grant write permission for repository contents (needed for commit actions)
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build SusOps.app with py2app
        run: python setup.py py2app

      - name: Package .app into zip
        run: zip -r SusOps.zip dist/SusOps.app

      - name: Compute SHA256
        id: sha
        run: echo "sum=$(shasum -a 256 SusOps.zip | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Determine version
        id: vars
        run: |
          tag="${{ github.ref_name }}"
          version="${tag#v}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: SusOps.zip
          asset_name: SusOps.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump Homebrew Cask
        run: |
          brew install homebrew/brew/bump-cask-pr
          brew bump-cask-pr \
            --cask-file ./Casks/susops.rb \
            --version "${{ steps.vars.outputs.version }}" \
            --sha256 "${{ steps.sha.outputs.sum }}" \
            --no-browse
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Cask bump
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "brew: bump SusOps to ${{ steps.vars.outputs.version }}"
