name: Build & Release SusOps

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
          persist-credentials: true
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build SusOps.app
        run: python setup.py py2app

      - name: Package .app into zip
        working-directory: ./dist
        run: zip -r SusOps.zip SusOps.app

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/SusOps.zip
          asset_name: SusOps.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-brew:
    name: bump brew cask version
    needs: build
    uses: mashb1t/homebrew-susops/.github/workflows/update-brew.yml@main
    with:
      update_cli: false
      update_mac: true
    secrets:
      brew_tap_token: ${{ secrets.BREW_TAP_TOKEN }}
